### ISSUE TITLE
raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")

### ISSUE THREAD

**Issue by YuZheng23** [oxwhirl/smac#120]
(marl) zhengyu@CentOS7-Login3 /workspace/S/zhengyu $ python -m smac.examples.random_agents
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 41381 -dataDir /workspace/S/zhengyu/StarCraftII/ -tempDir /tmp/sc-qz_sngvq/'
Starting up...
Startup Phase 1 complete
Fatal error encountered!
Backtrace:
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x65e838]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x65f270]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x65ecc2]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x5fc0d8]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x1b946e8]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x5f855c]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f7196329555]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x5f7f59]
Error condition code: '9'
Error suffix: 'Error'
Error preface: 'A fatal error occurred:'
Error failure: 'e_fileCorruptRepairable'
Error unique: '(NGDP:E_FAILURE)'
Error details: '"AppErrors.txt"'
Error description: 'AppErrors.txt'
WARNING:absl:SC2 isn't running, so bailing early on the websocket connection.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/examples/random_agents.py", line 44, in <module>
    main()
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/examples/random_agents.py", line 19, in main
    env.reset()
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/env/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/env/starcraft2/starcraft2.py", line 323, in _launch
    self._sc2_proc = self._run_config.start(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/run_configs/platforms.py", line 200, in start
    return super(Linux, self).start(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/run_configs/platforms.py", line 83, in start
    return sc_process.StarcraftProcess(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/sc_process.py", line 137, in __init__
    self._controller = remote_controller.RemoteController(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/remote_controller.py", line 142, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/stopwatch.py", line 205, in _stopwatch
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/remote_controller.py", line 176, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?
(marl) zhengyu@CentOS7-Login3 /workspace/S/zhengyu $ squeue --me
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 
            215103    nv-gpu     test  zhengyu  R      32:34      1 gpu-v02 
(marl) zhengyu@CentOS7-Login3 /workspace/S/zhengyu $ ssh gpu-v02
Creating directory '/home/S/zhengyu'.
Unable to create and initialize directory '/home/S/zhengyu'.
Last login: Tue Sep 19 10:26:29 2023 from 10.200.22.23
(base) zhengyu@gpu-v02 ~ $ cd /workspace/S/zhengyu
(base) zhengyu@gpu-v02 /workspace/S/zhengyu $ conda activate marl
(marl) zhengyu@gpu-v02 /workspace/S/zhengyu $ python -m smac.examples.random_agents
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 42830 -dataDir /workspace/S/zhengyu/StarCraftII/ -tempDir /tmp/sc-_1gvy92_/'
Starting up...
Startup Phase 1 complete
Fatal error encountered!
Backtrace:
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x65e838]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x65f270]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x65ecc2]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x5fc0d8]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x1b946e8]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x5f855c]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f5f04497555]
/workspace/S/zhengyu/StarCraftII/Versions/Base75689/SC2_x64[0x5f7f59]
Error condition code: '9'
Error suffix: 'Error'
Error preface: 'A fatal error occurred:'
Error failure: 'e_fileCorruptRepairable'
Error unique: '(NGDP:E_FAILURE)'
Error details: '"AppErrors.txt"'
Error description: 'AppErrors.txt'
WARNING:absl:SC2 isn't running, so bailing early on the websocket connection.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/examples/random_agents.py", line 44, in <module>
    main()
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/examples/random_agents.py", line 19, in main
    env.reset()
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/env/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/smac/env/starcraft2/starcraft2.py", line 323, in _launch
    self._sc2_proc = self._run_config.start(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/run_configs/platforms.py", line 200, in start
    return super(Linux, self).start(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/run_configs/platforms.py", line 83, in start
    return sc_process.StarcraftProcess(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/sc_process.py", line 137, in __init__
    self._controller = remote_controller.RemoteController(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/remote_controller.py", line 142, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/stopwatch.py", line 205, in _stopwatch
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/S/zhengyu/anaconda3/envs/marl/lib/python3.11/site-packages/pysc2/lib/remote_controller.py", line 176, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?

**Comment by YuZheng23** [comment]
I followed the tutorial exactly every step of the way and configured the smac environment without error, and the maps were downloaded new and placed in the corresponding locations, but this is the problem.

**Comment by winkkk248610** [comment]
May I ask if you have solved this problem? I have the same problem, if it is solved can you tell me the solution?

**Comment by BeiwenZhang** [comment]
I had the same problem and couldn't solve it
